CREATE TABLE `prospect_mail_domains` (
    `id` int NOT NULL AUTO_INCREMENT,
    `mail_domain` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    `company` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_swedish_ci DEFAULT NULL,
    `title` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
    `title_fetch_date` datetime DEFAULT NULL,
    `content_check_date` datetime DEFAULT NULL,
    `content_match` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
    `content_length` int DEFAULT NULL,
    `manual_review_required` enum('FALSE','TRUE') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'FALSE',
    `do_not_mail` enum('FALSE','TRUE') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'FALSE',
    `is_provider_domain` enum('FALSE','TRUE') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'FALSE',
    `is_reachable` enum('FALSE','TRUE') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'TRUE',
    `has_mx_entry` enum('FALSE','TRUE') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'TRUE',
    `has_ssl_certificate` enum('FALSE','TRUE') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
    `content_unsuitable` enum('FALSE','TRUE') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'FALSE',
    `reachable_last_check_date` datetime DEFAULT NULL,
    `mx_entry_last_check_date` datetime DEFAULT NULL,
    `language` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
    `language_check_date` datetime DEFAULT NULL,
    `registrant_country` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
    `registrant_country_check_date` datetime DEFAULT NULL,
    `has_prospects` enum('FALSE','TRUE') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'FALSE',
    `phone_number_country_code` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_swedish_ci DEFAULT NULL,
    `phone_number` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_swedish_ci DEFAULT NULL,
    `phone_number_last_check_date` datetime DEFAULT NULL,
    `phone_number_research_employee_id` int DEFAULT NULL,
    `phone_number_export_date` datetime DEFAULT NULL,
    `category_1` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
    `category_2` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
    `category_3` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
    `category_confidence` float DEFAULT NULL,
    `content_snippet` varchar(5000) COLLATE utf8mb4_general_ci DEFAULT NULL,
    `language_detected` varchar(2) COLLATE utf8mb4_general_ci DEFAULT NULL,
    `review_employee_id` int DEFAULT NULL,
    `manual_review_finished_date` datetime DEFAULT NULL,
    `manual_review_screenshot_fetch_date` datetime DEFAULT NULL,
    `last_hunter_io_contacts_research_date` datetime DEFAULT NULL,
    `last_minelead_io_contacts_research_date` datetime DEFAULT NULL,
    `last_snov_io_contacts_research_date` datetime DEFAULT NULL,
    `receiving_mail_server` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL,
    `last_receiving_mail_server_check_date` datetime DEFAULT NULL,
    `last_traffic_info_check_date` datetime DEFAULT NULL,
    `paid_ads_traffic` int DEFAULT NULL,
    `paid_ads_keyword_number` int DEFAULT NULL,
    `organic_traffic` int DEFAULT NULL,
    `organic_keyword_number` int DEFAULT NULL,
    `premium` enum('FALSE','TRUE') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'FALSE',
    `creation_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uidx_mail_domain` (`mail_domain`),
    KEY `fk_prospect_mail_domains_phone_number_research_employee_id` (`phone_number_research_employee_id`),
    CONSTRAINT `fk_prospect_mail_domains_phone_number_research_employee_id` FOREIGN KEY (`phone_number_research_employee_id`) REFERENCES `employees` (`id`)
    CONSTRAINT `fk_prospect_mail_domains_review_employee_id` FOREIGN KEY (`review_employee_id`) REFERENCES `employees` (`id`),
    INDEX `idx_mail_domain` (`mail_domain`),
    INDEX `idx_language_registrant_country` (`language`, `registrant_country`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

# mysql users
CREATE USER 'autoranker_www'@'%' IDENTIFIED BY 'password';
GRANT SELECT ON gsqt_core.prospect_mail_domains TO 'autoranker_www'@'%';
